package info.md7.java.homeworks.hw_2;

public enum  Nationality {

    AFGHAN, ALBANIAN, ALGERIAN, ARGENTINE, ARGENTINIAN, AUSTRALIAN, AUSTRIAN,
    AZERBAIJANI, BANGLADESHI, BELGIAN, BOLIVIAN, BATSWANA, BRAZILIAN,
    BULGARIAN, CAMBODIAN, CAMEROONIAN, CANADIAN, CHILEAN, CHINESE, COLOMBIAN,
    COSTA_RICAN, CROATIAN, CUBAN, CZECH, DANISH, DOMINICAN, ECUADORIAN, EGYPTIAN,
    SALVADORIAN, ENGLISH, ESTONIAN, ETHIOPIAN, FIJIAN, FINNISH, FRENCH, GERMAN,
    GHANAIAN, GREEK, GUATEMALAN, HAITIAN, HONDURAN, HUNGARIAN, ICELANDIC, INDIAN,
    INDONESIAN, IRANIAN, IRAQI, IRISH, ISRAELI, ITALIAN, JAMAICAN, JAPANESE, JORDANIAN,
    KENYAN, KUWAITI, LAO, LATVIAN, LEBANESE, LIBYAN, LITHUANIAN, MALAGASY, MALAYSIAN, MALIAN,
    MALTESE, MEXICAN, MONGOLIAN, MOROCCAN, MOZAMBICAN, NAMIBIAN, NEPALESE, DUTCH, NEW_ZEALAND,
    NICARAGUAN, NIGERIAN, NORWEGIAN, PAKISTANI, PANAMANIAN, PARAGUAYAN, PERUVIAN, PHILIPPINE,
    POLISH, PORTUGUESE, ROMANIAN, RUSSIAN, SAUDI, SCOTTISH, SENEGALESE, SERBIAN, SINGAPOREAN,
    SLOVAK, SOUTH_AFRICAN, KOREAN, SPANISH, SRI_LANKAN, SUDANESE, SWEDISH, SWISS, SYRIAN,
    TAIWANESE, TAJIKISTANI, THAI, TONGAN, TUNISIAN, TURKISH, UKRAINIAN, EMIRATI, BRITISH,
    AMERICAN, URUGUAYAN, VENEZUELAN, VIETNAMESE, WELSH, ZAMBIAN, ZIMBABWEAN, UNDEFINED;

}
